[project]
name = "browser-use"
description = "Let LLMs interact with websites through a simple interface"
authors = [
    { name = "Gregor Zunic" }
]
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "MainContentExtractor>=0.0.4",
    "Selenium-Screenshot>=2.1.0",
    "beautifulsoup4>=4.12.3", 
    "langchain>=0.3.7",
    "langchain-openai>=0.2.5",
    "langchain-anthropic>=0.2.4",
    "langchain-fireworks>=0.2.5",
    "pydantic>=2.9.2",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "selenium>=4.26.1",
    "webdriver-manager>=4.0.2",
    "lxml_html_clean>=0.3.1"
]

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
