[project]
name = "browser-use"
version = "0.1.0"
description = "Open-Source Web Automation with LLMs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
