name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-syntax:
    name: lint/Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv and cache packages
        uses: astral-sh/setup-uv@v5
      - run: uv run ruff check --no-fix --select PLE

  lint-style:
    name: lint/Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv and cache packages
        uses: astral-sh/setup-uv@v5
      - run: uv run ruff format
      - run: uv run pre-commit run --all-files

  lint-typecheck:
    name: lint/pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv and cache packages
        uses: astral-sh/setup-uv@v5
      - run: uv run pyright



        
